In [38]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv("C:\\Users\\skk\\Downloads\\archive (4)\\retail_store_inventory.csv")

df

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73095,2024-01-01,S005,P0016,Furniture,East,96,8,127,18.46,73.73,20,Snowy,0,72.45,Winter
73096,2024-01-01,S005,P0017,Toys,North,313,51,101,48.43,82.57,10,Cloudy,0,83.78,Autumn
73097,2024-01-01,S005,P0018,Clothing,West,278,36,151,39.65,11.11,10,Rainy,0,10.91,Winter
73098,2024-01-01,S005,P0019,Toys,East,374,264,21,270.52,53.14,20,Rainy,0,55.80,Spring
73099,2024-01-01,S005,P0020,Groceries,East,117,6,165,2.33,78.39,20,Rainy,1,79.52,Spring

In [42]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [43]:
df.shape

(73100, 15)

In [44]:
df.columns

Index(['Date', 'Store ID', 'Product ID', 'Category', 'Region',
       'Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast',
       'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion',
       'Competitor Pricing', 'Seasonality'],
      dtype='object')

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  object
 1   Store ID            73100 non-null  object
 2   Product ID          73100 non-null  object
 3   Category            73100 non-null  object
 4   Region              73100 non-null  object
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  object
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  object
dtypes: float64(3), int64(5), object(7)
memory usage: 8.4+ MB

In [46]:
df.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Weather Condition     0
Holiday/Promotion     0
Competitor Pricing    0
Seasonality           0
dtype: int64

In [47]:
df.duplicated().sum()

np.int64(0)

In [48]:
df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (73100, 15)

In [49]:
df["Date"].dtype

dtype('O')

In [50]:
df["Date"] = pd.to_datetime(df["Date"])

In [51]:
df["Date"].dtype

dtype('<M8[ns]')

In [52]:
numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    print(col, ":", (df[col] < 0).sum())

Inventory Level : 0
Units Sold : 0
Units Ordered : 0
Demand Forecast : 673
Price : 0
Discount : 0
Holiday/Promotion : 0
Competitor Pricing : 0

In [53]:
df[numeric_cols].isnull().sum()

Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Holiday/Promotion     0
Competitor Pricing    0
dtype: int64

In [54]:
categorical_cols = df.select_dtypes(include="object").columns

df[categorical_cols].isnull().sum()

Store ID             0
Product ID           0
Category             0
Region               0
Weather Condition    0
Seasonality          0
dtype: int64

In [55]:
df.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Weather Condition     0
Holiday/Promotion     0
Competitor Pricing    0
Seasonality           0
dtype: int64

In [56]:
print("Missing dates:", df["Date"].isnull().sum())
print("Minimum date:", df["Date"].min())
print("Maximum date:", df["Date"].max())

Missing dates: 0
Minimum date: 2022-01-01 00:00:00
Maximum date: 2024-01-01 00:00:00

In [60]:
for col in categorical_cols:
    print(col, ":", (df[col].astype(str).str.strip() == "").sum())

Store ID : 0
Product ID : 0
Category : 0
Region : 0
Weather Condition : 0
Seasonality : 0

In [61]:
for col in categorical_cols:
    df[col] = df[col].str.strip()

In [62]:
for col in categorical_cols:
    print("\n", col)
    print(df[col].unique())

 Store ID
['S001' 'S002' 'S003' 'S004' 'S005']

 Product ID
['P0001' 'P0002' 'P0003' 'P0004' 'P0005' 'P0006' 'P0007' 'P0008' 'P0009'
 'P0010' 'P0011' 'P0012' 'P0013' 'P0014' 'P0015' 'P0016' 'P0017' 'P0018'
 'P0019' 'P0020']

 Category
['Groceries' 'Toys' 'Electronics' 'Furniture' 'Clothing']

 Region
['North' 'South' 'West' 'East']

 Weather Condition
['Rainy' 'Sunny' 'Cloudy' 'Snowy']

 Seasonality
['Autumn' 'Summer' 'Winter' 'Spring']

In [63]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [64]:
print("Dataset Shape:", df.shape)
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())
print("Date Data Type:", df["Date"].dtype)

Dataset Shape: (73100, 15)
Missing Values: 0
Duplicate Rows: 0
Date Data Type: datetime64[ns]

In [ ]:
df.to_csv("../data/cleaned_sales.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

: