In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/cleaned_sales.csv")

df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [3]:
df["Date"] = pd.to_datetime(df["Date"])

print("Date Data Type:", df["Date"].dtype)

Date Data Type: datetime64[ns]

In [4]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["DayOfWeek"] = df["Date"].dt.dayofweek

df[["Date", "Year", "Month", "Day", "DayOfWeek"]].head()

        Date  Year  Month  Day  DayOfWeek
0 2022-01-01  2022      1    1          5
1 2022-01-01  2022      1    1          5
2 2022-01-01  2022      1    1          5
3 2022-01-01  2022      1    1          5
4 2022-01-01  2022      1    1          5

In [5]:
df["IsWeekend"] = df["DayOfWeek"].isin([5, 6]).astype(int)

df[["Date", "DayOfWeek", "IsWeekend"]].head(10)

        Date  DayOfWeek  IsWeekend
0 2022-01-01          5          1
1 2022-01-01          5          1
2 2022-01-01          5          1
3 2022-01-01          5          1
4 2022-01-01          5          1
5 2022-01-01          5          1
6 2022-01-01          5          1
7 2022-01-01          5          1
8 2022-01-01          5          1
9 2022-01-01          5          1

In [ ]:
df["Revenue"] = df["Units Sold"] * df["Unit Price"]

df[["Units Sold", "Unit Price", "Revenue"]].head()

KeyError: ' Price'

In [10]:
# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Create Revenue feature
df["Revenue"] = df["Units Sold"] * df["Price"]

# Check result
df[["Units Sold", "Price", "Revenue"]].head()

   Units Sold  Price  Revenue
0         127  33.50  4254.50
1         150  63.01  9451.50
2          65  27.99  1819.35
3          61  32.72  1995.92
4          14  73.64  1030.96

In [11]:
df["Discount Amount"] = df["Price"] * df["Discount"]

df[["Price", "Discount", "Discount Amount"]].head()

   Price  Discount  Discount Amount
0  33.50        20            670.0
1  63.01        20           1260.2
2  27.99        10            279.9
3  32.72        10            327.2
4  73.64         0              0.0

In [12]:
df["Net Revenue"] = df["Revenue"] - df["Discount Amount"]

df[["Revenue", "Discount Amount", "Net Revenue"]].head()

   Revenue  Discount Amount  Net Revenue
0  4254.50            670.0      3584.50
1  9451.50           1260.2      8191.30
2  1819.35            279.9      1539.45
3  1995.92            327.2      1668.72
4  1030.96              0.0      1030.96

In [13]:
df = df.sort_values(
    by=["Store ID", "Product ID", "Date"]
).reset_index(drop=True)

df[["Store ID", "Product ID", "Date", "Units Sold"]].head(10)

  Store ID Product ID       Date  Units Sold
0     S001      P0001 2022-01-01         127
1     S001      P0001 2022-01-02          81
2     S001      P0001 2022-01-03           5
3     S001      P0001 2022-01-04          58
4     S001      P0001 2022-01-05         147
5     S001      P0001 2022-01-06          37
6     S001      P0001 2022-01-07         107
7     S001      P0001 2022-01-08           2
8     S001      P0001 2022-01-09         350
9     S001      P0001 2022-01-10          36

In [14]:
df["Lag_1_Day"] = (
    df.groupby(["Store ID", "Product ID"])["Units Sold"]
      .shift(1)
)

df[["Store ID", "Product ID", "Date", "Units Sold", "Lag_1_Day"]].head(10)

  Store ID Product ID       Date  Units Sold  Lag_1_Day
0     S001      P0001 2022-01-01         127        NaN
1     S001      P0001 2022-01-02          81      127.0
2     S001      P0001 2022-01-03           5       81.0
3     S001      P0001 2022-01-04          58        5.0
4     S001      P0001 2022-01-05         147       58.0
5     S001      P0001 2022-01-06          37      147.0
6     S001      P0001 2022-01-07         107       37.0
7     S001      P0001 2022-01-08           2      107.0
8     S001      P0001 2022-01-09         350        2.0
9     S001      P0001 2022-01-10          36      350.0

In [15]:
df["Lag_7_Days"] = (
    df.groupby(["Store ID", "Product ID"])["Units Sold"]
      .shift(7)
)

df[[
    "Store ID",
    "Product ID",
    "Date",
    "Units Sold",
    "Lag_1_Day",
    "Lag_7_Days"
]].head(15)

   Store ID Product ID       Date  Units Sold  Lag_1_Day  Lag_7_Days
0      S001      P0001 2022-01-01         127        NaN         NaN
1      S001      P0001 2022-01-02          81      127.0         NaN
2      S001      P0001 2022-01-03           5       81.0         NaN
3      S001      P0001 2022-01-04          58        5.0         NaN
4      S001      P0001 2022-01-05         147       58.0         NaN
5      S001      P0001 2022-01-06          37      147.0         NaN
6      S001      P0001 2022-01-07         107       37.0         NaN
7      S001      P0001 2022-01-08           2      107.0       127.0
8      S001      P0001 2022-01-09         350        2.0        81.0
9      S001      P0001 2022-01-10          36      350.0         5.0
10     S001      P0001 2022-01-11          16       36.0        58.0
11     S001      P0001 2022-01-12         104       16.0       147.0
12     S001      P0001 2022-01-13          80      104.0        37.0
13     S001      P0001 2022-01-14         177       80.0       107.0
14     S001      P0001 2022-01-15         176      177.0         2.0

In [16]:
df["Rolling_7_Days"] = (
    df.groupby(["Store ID", "Product ID"])["Units Sold"]
      .transform(lambda x: x.shift(1).rolling(7).mean())
)

df[[
    "Store ID",
    "Product ID",
    "Date",
    "Units Sold",
    "Lag_1_Day",
    "Lag_7_Days",
    "Rolling_7_Days"
]].head(15)

,Store ID,Product ID,Date,Units Sold,Lag_1_Day,Lag_7_Days,Rolling_7_Days
0,S001,P0001,2022-01-01,127,NaN,NaN,NaN
1,S001,P0001,2022-01-02,81,127.0,NaN,NaN
2,S001,P0001,2022-01-03,5,81.0,NaN,NaN
3,S001,P0001,2022-01-04,58,5.0,NaN,NaN
4,S001,P0001,2022-01-05,147,58.0,NaN,NaN
5,S001,P0001,2022-01-06,37,147.0,NaN,NaN
6,S001,P0001,2022-01-07,107,37.0,NaN,NaN
7,S001,P0001,2022-01-08,2,107.0,127.0,80.285714
8,S001,P0001,2022-01-09,350,2.0,81.0,62.428571
9,S001,P0001,2022-01-10,36,350.0,5.0,100.857143
10,S001,P0001,2022-01-11,16,36.0,58.0,105.285714
11,S001,P0001,2022-01-12,104,16.0,147.0,99.285714
12,S001,P0001,2022-01-13,80,104.0,37.0,93.142857
13,S001,P0001,2022-01-14,177,80.0,107.0,99.285714
14,S001,P0001,2022-01-15,176,177.0,2.0,109.285714

In [17]:
print("Missing Values in Feature Engineered Data:")
print(df.isnull().sum())

Missing Values in Feature Engineered Data:
Date                    0
Store ID                0
Product ID              0
Category                0
Region                  0
Inventory Level         0
Units Sold              0
Units Ordered           0
Demand Forecast         0
Price                   0
Discount                0
Weather Condition       0
Holiday/Promotion       0
Competitor Pricing      0
Seasonality             0
Year                    0
Month                   0
Day                     0
DayOfWeek               0
IsWeekend               0
Revenue                 0
Discount Amount         0
Net Revenue             0
Lag_1_Day             100
Lag_7_Days            700
Rolling_7_Days        700
dtype: int64

In [18]:
df = df.dropna(
    subset=["Lag_1_Day", "Lag_7_Days", "Rolling_7_Days"]
).reset_index(drop=True)

print("Shape after removing lag missing values:", df.shape)
print("Remaining missing values:", df.isnull().sum().sum())

Shape after removing lag missing values: (72400, 26)
Remaining missing values: 0

In [19]:
print("Dataset Shape:", df.shape)

print("\nFeature Columns:")
print(df.columns.tolist())

print("\nSample Data:")
df.head()

Dataset Shape: (72400, 26)

Feature Columns:
['Date', 'Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast', 'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion', 'Competitor Pricing', 'Seasonality', 'Year', 'Month', 'Day', 'DayOfWeek', 'IsWeekend', 'Revenue', 'Discount Amount', 'Net Revenue', 'Lag_1_Day', 'Lag_7_Days', 'Rolling_7_Days']

Sample Data:

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,...,Month,Day,DayOfWeek,IsWeekend,Revenue,Discount Amount,Net Revenue,Lag_1_Day,Lag_7_Days,Rolling_7_Days
0,2022-01-08,S001,P0001,Furniture,East,231,2,119,0.84,66.30,...,1,8,5,1,132.60,1326.00,-1193.40,107.0,127.0,80.285714
1,2022-01-09,S001,P0001,Electronics,South,373,350,178,352.24,41.72,...,1,9,6,1,14602.00,0.00,14602.00,2.0,81.0,62.428571
2,2022-01-10,S001,P0001,Electronics,West,327,36,132,39.50,32.68,...,1,10,0,0,1176.48,163.40,1013.08,350.0,5.0,100.857143
3,2022-01-11,S001,P0001,Furniture,West,101,16,193,16.11,27.53,...,1,11,1,0,440.48,137.65,302.83,36.0,58.0,105.285714
4,2022-01-12,S001,P0001,Toys,South,145,104,189,100.32,92.92,...,1,12,2,0,9663.68,0.00,9663.68,16.0,147.0,99.285714

In [20]:
df.to_csv("../data/feature_engineered_data.csv", index=False)

print("Feature-engineered dataset saved successfully!")

Feature-engineered dataset saved successfully!

In [ ]:
print("========== FEATURE ENGINEERING FINAL VALIDATION ==========")

print("Dataset Shape:", df.shape)
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())

print("\nNew Features:")
print([
    "Year",
    "Month",
    "Day",
    "DayOfWeek",
    "IsWeekend",
    "Revenue",
    "Discount Amount",
    "Net Revenue",
    "Lag_1_Day",
    "Lag_7_Days",
    "Rolling_7_Days"
])

========== FEATURE ENGINEERING FINAL VALIDATION ==========
Dataset Shape: (72400, 26)
Missing Values: 0
Duplicate Rows: 0

New Features:
['Year', 'Month', 'Day', 'DayOfWeek', 'IsWeekend', 'Revenue', 'Discount Amount', 'Net Revenue', 'Lag_1_Day', 'Lag_7_Days', 'Rolling_7_Days']

: